const actionTypes = {
  SET_TRANSACTIONS: "SET_TRANSACTIONS",
  SET_FILTERED_TRANSACTIONS: "SET_FILTERED_TRANSACTIONS",
  SET_SUBMITING: "SET_SUBMITING",
  SET_TERM: "SET_TERM",
  SET_SORT_TYPE: "SET_SORT_TYPE",
};

export { actionTypes };
